<form class="form-horizontal">
	<div class="form-group">
		<label for="nombre">Nombre</label>
		<div class="col-sm-12">
			<input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombre">
		</div>
	</div>
	<div class="form-group">
		<label for="direccion">Dirección</label><br>
		<div class="col-sm-4">
			Calle: <input type="text" class="form-control" name="calle" id="calle" placeholder="Calle">
		</div>
		<div class="col-sm-2">
			No. Exterior: <input type="text" class="form-control" name="num_exterior" id="num_exterior" placeholder="No. Exterior">
		</div>
		<div class="col-sm-2">
			No. Interior: <input type="text" class="form-control" name="num_interior" id="num_interior" placeholder="No. Interior">
		</div>
		<div class="col-sm-4">
			Colonia: <input type="text" class="form-control" name="colonia" id="colonia" placeholder="Colonia">
		</div>
		<div class="col-sm-4">
			Delegacion/Municipio: <input type="text" class="form-control" name="delegacion_municipio" id="delegacion_municipio" placeholder="Delegacion/Municipio">
		</div>
		<div class="col-sm-4">
			Estado: <input type="text" class="form-control" name="estado" id="estado" placeholder="Estado">
		</div>
		<div class="col-sm-4">
			Código Postal: <input type="text" class="form-control" name="cp" id="cp" placeholder="Código Postal">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			Correo: <input type="text" class="form-control" name="correo" id="correo" placeholder="Correo">
		</div>
	</div>
	<div class="form-group" id="telefonos">
		<label for="direccion">Teléfonos:</label><br>
		<div class="col-xs-4">
			Lada: <input type="text" class="form-control lada" placeholder="Lada">
		</div>
		<div class="col-sm-8">
			Teléfono: <input type="text" class="form-control numero" placeholder="Teléfono">
		</div>
		<button type="button" class="btn btn-success btn-md" id="add-telephone" onclick="add_telephone()">
	        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Teléfono
	    </button>
	</div>
	<button type="submit" class="btn btn-default">Guardar</button>
</form>