<form id="contact_<?= $this->contacts[0]->getId() ?>" class="form-horizontal" action="addressbook/updatec" method="post" onsubmit="validate_form(this, event);">
	<h4><span class="label label-info">Todos los campos con asterisco (*) son requeridos</span></h4>
	<div class="form-group">
		<label for="nombre">*Nombre</label>
		<div class="col-sm-12 required">
			<input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombre" value="<?= $this->contacts[0]->getNombre() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
	</div>
	<div class="form-group">
		<label for="direccion">*Dirección</label><br>
		<div class="col-sm-4 required">
			Calle: <input type="text" class="form-control" name="calle" id="calle" placeholder="Calle" value="<?= $this->direcciones[0]->getCalle() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
		<div class="col-sm-2">
			*No. Exterior: <input type="text" class="form-control" name="num_exterior" id="num_exterior" placeholder="No. Exterior" value="<?= $this->direcciones[0]->getNumExt() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
		<div class="col-sm-2">
			No. Interior: <input type="text" class="form-control" name="num_interior" id="num_interior" placeholder="No. Interior" value="<?= $this->direcciones[0]->getNumInt() ?>">
		</div>
		<div class="col-sm-4 required">
			*Colonia: <input type="text" class="form-control" name="colonia" id="colonia" placeholder="Colonia" value="<?= $this->direcciones[0]->getColonia() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
		<div class="col-sm-4 required">
			*Delegacion/Municipio: <input type="text" class="form-control" name="delegacion_municipio" id="delegacion_municipio" placeholder="Delegacion/Municipio" value="<?= $this->direcciones[0]->getDelegacionMunicipio() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
		<div class="col-sm-4 required">
			*Estado: <input type="text" class="form-control" name="estado" id="estado" placeholder="Estado" value="<?= $this->direcciones[0]->getEstado() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
		<div class="col-sm-4 required">
			*Código Postal: <input type="text" class="form-control" name="cp" id="cp" placeholder="Código Postal" value="<?= $this->direcciones[0]->getCp() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12 required">
			*Correo: <input type="text" class="form-control" name="correo" id="correo" placeholder="Correo" value="<?= $this->correos[0]->getCorreo() ?>">
			<h4 class="error-message"><span class="label label-danger">Campo requerido</span></h4>
		</div>
	</div>
	<div class="form-group" id="telefonos">
		<label for="direccion">Teléfonos:</label><br>
		<div class="col-xs-4">
			Lada: <input type="text" maxlength="3" class="form-control lada" placeholder="Lada">
		</div>
		<div class="col-sm-8">
			Teléfono: <input type="text" maxlength="12" class="form-control numero" placeholder="Teléfono">
		</div>
		<button type="button" class="btn btn-success btn-md" id="add-telephone" onclick="add_telephone()">
	        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Teléfono
	    </button>
	</div>
	<button type="submit" class="btn btn-primary btn-lg">Actualizar</button>
</form>