<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 text-center">
            <button type="button" class="btn btn-success btn-lg">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Contacto
            </button>
        </div>
        <div class="col-md-6 text-center">
            <button type="button" class="btn btn-info btn-lg">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span> Consultar
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
            <div id="dinamic-content">
                <h1>Añadir y consultar contactos</h1>
            </div>
        </div>
    </div>
</div>