<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 text-center">
            <button id="addContact" type="button" class="btn btn-success btn-lg">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar Contacto
            </button>
        </div>
        <div class="col-sm-6 text-center">
            <button id="getContact" type="button" class="btn btn-info btn-lg">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span> Consultar
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
            <div class="row">
                <div class="col-sm-12" id="dinamic-content" style="display:none;">
                </div>
            </div>
        </div>
    </div>
</div>