<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Agenda de Contactos</title>
  <?= $this->headScript()->appendFile('/js/jquery.min.js')->appendFile('/js/bootstrap.min.js') ?>
  <?= $this->headLink()->appendStylesheet('/css/bootstrap.min.css')->appendStylesheet('/css/bootstrap-theme.min.css')->appendStylesheet('/css/styles.css') ?>
</head>
<body>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header text-center">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Agenda de contactos</a>
		</div>
	</div>
</nav>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>